### ISSUE TITLE
Openshift playground used for conference demo June 8th 08:00 - 16:00 get

### ISSUE THREAD

**Issue by WianVos** [openshift-instruqt/instruqt#101]
Hey guys, 

I would like to have the following workshops on hot standby on June 8th from 08:00 until about 16:00 

Workshops:
Getting started with Quarkus
Quarkus for Spring Boot developers

The event we will be at is JSpring in the Netherlands where Burr will do a session. 
We will be running about 8 Chromebooks ... 
Regards

Wian Vos

**Comment by danieloh30** [comment]
Hi @WianVos 

Thanks for choosing the Quarkus tracks! Just out of curiosity, which URL will you use to access the tracks? e.g. embedded URL in RHD or directly Instruqt?

https://developers.redhat.com/courses/quarkus/getting-started
https://developers.redhat.com/courses/quarkus/spring
If you want to use the embedded UI in RHD, you should be aware that you can't restart from the beginning if you stop the track in the middle of the track before the session timeout (30 min by default)

AFAIK, 2 tracks are already set as hotstarts. Getting-start is 3 and Spring one is 1 hot start.

**Comment by blues-man** [comment]
@danieloh30  we usually create private invites with anonymous access so that the list of tracks are composed by the Instruqt UI. 
@WianVos the hot starts are configured for the request timeframe

**Comment by danieloh30** [comment]
Yeah, that's what I thought too. But unfortunately I had no private links at KubeCon EU :(

**Comment by cedricclyburn** [comment]
Event has passed, closing out ticket 👍
