### ISSUE TITLE
`GRAALVM_HOME` is not defined in the Quarkus `getting-started` lab environment

### ISSUE THREAD

**Issue by evanshortiss** [openshift-instruqt/instruqt#110]
When running the echo command [defined here](https://github.com/openshift-instruqt/instruqt/blame/master/developing-with-quarkus/getting-started/04-04-build-native/assignment.md#L38) it prints a blank line. It seems as though the variable is not defined. This hints that there's an issue in the environment setup script(s).

This is not a huge issue since the assignment is still working thanks to Quarkus falling back to using a container via Podman to perform the native build if the host machine does not have the necessary dependencies.

**Comment by ryanj** [comment]
Thanks for the bug report and PR
