### ISSUE TITLE
developing-with-quarkus/getting-started minor issues/typos

### ISSUE THREAD

**Issue by evanshortiss** [openshift-instruqt/instruqt#113]
1. "However, this compilation time is only incurred once, when the application starts." - I think the end of this sentence should be "when you build the application"? The phrase "when the application starts" suggests it is each time a Pod or process is started, which would be a downside.
2. "One of th key features of applications running under Quarkus is that they consume small amounts of memory." - typo in the word "the" => "th"
3. "You've learned how to built a Java" - typo "build"

**Comment by cedricclyburn** [comment]
Looks like these changes have been merged, closing issue 👍
