### ISSUE TITLE
Getting the Web Site not available error for the Web Console here: https://play.instruqt.com/openshift/tracks/developing-with-quarkus-reactive-sql/challenges/02-remote-dev/assignment

### ISSUE THREAD

**Issue by reselbob** [openshift-instruqt/instruqt#120]
Getting the Web Site not available error for the Web Console here: https://play.instruqt.com/openshift/tracks/developing-with-quarkus-reactive-sql/challenges/02-remote-dev/assignment

When I run `oc login -u admin -p admin` in there terminal window it's as if the cluster is not there

**Comment by evanshortiss** [comment]
Joined @reselbob on a call to look into this. We started a new run, and seems like the environment got stuck at the ingresscontroller delete step:

```
2022-06-16T19:39:20Z hwurcikctelf INFO: setup-crc: ingress.config.openshift.io/cluster patched
2022-06-16T19:39:20Z hwurcikctelf INFO: setup-crc: + sleep 30
2022-06-16T19:39:50Z hwurcikctelf INFO: setup-crc: + oc delete -n openshift-ingress-operator ingresscontroller/default
2022-06-16T19:39:50Z hwurcikctelf INFO: setup-crc: ingresscontroller.operator.openshift.io "default" deleted
```

I waited for 20 minutes, but no more logs printed after this.

**Comment by evanshortiss** [comment]
Possibly related? 

https://github.com/kubernetes/kubernetes/issues/69851

**Comment by blues-man** [comment]
Let's try the same procedure as per the Kafka one, aka instruqt track delete, Instruqt track push

**Comment by cedricclyburn** [comment]
Looks like this issue has been resolved, I'm able to log into the web console now! Closing out 👍
