### ISSUE TITLE
Kubernetes fundamentals workshop - June 23 - 11:00AM to 12:20PM Australian Eastern Daylight Time (AEDT)

### ISSUE THREAD

**Issue by lijcam** [openshift-instruqt/instruqt#124]
Opening this for visibility. I'll setup the hot-starts and invites on my side.
Kubernetes fundamentals workshop - June 23 - 11:00AM to 12:20PM Australian Eastern Daylight Time (AEDT)
23 attendees

@blues-man

**Comment by ryanj** [comment]
Thanks for the visibility!

**Comment by cedricclyburn** [comment]
Event has passed, closing out ticket 👍
