### ISSUE TITLE
Search term 'OpenShift Pipelines Operator' no longer supported

### ISSUE THREAD

**Issue by reselbob** [openshift-instruqt/instruqt#138]
Hi:

On this Instruqt: https://developers.redhat.com/courses/gitops/getting-started-openshift-pipelines:

In Step 1, there is an the following language:

---

Use the Filter by keyword box to search for `OpenShift Pipelines Operator` in the catalog. Click the OpenShift Pipelines Operator tile.

---

Seems that the search term `OpenShift Pipelines Operator` is no longer supported.

Here is a screencast internal to Red Hat the demonstrates the issue:

https://drive.google.com/file/d/1tWQ7xMyyhsD5ilhVqvqbpW1HMii7GEKR/view?usp=sharing

**Comment by cedricclyburn** [comment]
Looks like the instructions to install via the CLI are also broken, fixing that as well...

**Comment by cedricclyburn** [comment]
Closing due to fix with #155, thank you for bringing this up!
