### ISSUE TITLE
Can't login to ArgoCD from command line in Instuqt track: 

### ISSUE THREAD

**Issue by reselbob** [openshift-instruqt/instruqt#139]
Hi:

In the second topic, _Connecting to ArgoCD_, of the Instruqt track Getting Started with ArgoCD which you can find here: [getting-started-argocd-and-openshift-gitops-operator
](https://developers.redhat.com/courses/gitops/getting-started-argocd-and-openshift-gitops-operator)

at the instruction: `argocd login $ARGOCD_SERVER_URL`

I get the error:

```
FATA[0579] rpc error: code = Unauthenticated desc = Invalid username or password
```

Here is a screencast video accessible to those at Red Hat that demonstrates the issue. Also, that video has some additional commentary.

https://drive.google.com/file/d/1wnIkAT6I0qMHdKD-iLiBOQWdlI2jeYnf/view?usp=sharing

**Comment by ryanj** [comment]
Thanks for filing this report!

Sorry for the delay on this ... Cedric and I have finally had a chance to add some clarifications to the argocd login process.

Your main blocker, the credentials mismatch, can be solved by using a different admin password for argocd.  The argocd admin password is printed to the console in the step preceding `argocd login`.  

This track should be working correctly now.
