### ISSUE TITLE
Start button doesn’t show 

### ISSUE THREAD

**Issue by blues-man** [openshift-instruqt/instruqt#14]
UI bug where the start button doesn’t show (I suspect it’s the “Launching environment” text doesn’t show)

**Comment by amochtar** [comment]
@blues-man can you link to a track that has this behavior? I'm having a hard time reproducing this.

**Comment by blues-man** [comment]
it happens for instance here:
https://play.instruqt.com/openshift/tracks/developing-with-quarkus-getting-started/challenges/01-create-project/

when I do some changes and then I push those, the green button disappear so I don't know if it's ready or creating the env

**Comment by dewan-ahmed** [comment]
![Screen Shot 2021-11-15 at 3 48 04 PM](https://user-images.githubusercontent.com/30604461/141844597-0a203ffc-cb22-4280-b3c9-9ec67b2fe198.png)
I have seen this glitch on multiple tracks:
- https://play.instruqt.com/openshift/tracks/gitops-kustomize
- https://play.instruqt.com/openshift/tracks/gitops-getting-started

I tried clearing cache and connecting from Incognito but this glitch remains.

**Comment by amochtar** [comment]
My suspicion is that this only happens when pushing a track, while an instance is already running. @blues-man/@dewan-ahmed can you confirm that you see this when actively changing a track? Or do you also see this behavior in other cases?

**Comment by cedricclyburn** [comment]
Closing out this issue, it had sometimes occurred last year when pushing changes to a track and without hitting the "Stop/Quit" track button to reload changes
