### ISSUE TITLE
Devoxx Belgium Hot Starts - 11th to 13th October

### ISSUE THREAD

**Issue by evanshortiss** [openshift-instruqt/instruqt#140]
**Dates / Times**

* Tue. 11 Oct. 08:00 - 19:30
* Wed. 12 Oct. 08:00 - 20:00 
* Thu. 13 Oct. 08:00 - 19:30 

**Courses**

* Getting Started with Quarkus
* Quarkus for Spring Boot Developers
* Getting Started with OpenShift for Developers

**Comment by cedricclyburn** [comment]
Closing out since event has passed. Looks like 15% of quarkus sandboxes claimed, and 100% of getting started with openshift claimed.
