### ISSUE TITLE
Can't login to the Ansible UI in the track: Get started with Ansible Automation Mesh

### ISSUE THREAD

**Issue by reselbob** [openshift-instruqt/instruqt#141]
https://developers.redhat.com/learn/get-started-ansible-automation-mesh

In the first topic, **Automation mesh overview**,  when I enter the published credentials `admin`/`ansible123!` I get a login error, like so:

![Screen Shot 2022-09-08 at 10 45 57 AM](https://user-images.githubusercontent.com/1110569/189190873-758c0a1e-11c6-477a-bf48-3b4d8bbcc60f.png)

This screencast demonstrates the error:

https://drive.google.com/file/d/1JTZycyTJdMz_-E-0YJVXEQLvdPrD_tG7/view?usp=sharing

**Comment by cedricclyburn** [comment]
Looks as if the team has fixed this issue as of about two weeks ago, https://github.com/ansible/instruqt/tree/devel/tracks/getting-started-mesh, going to close this.
