### ISSUE TITLE
FATA[0000] failed to initialize project: already initialized - Hands on lab operator

### ISSUE THREAD

**Issue by thomassuedbroecker** [openshift-instruqt/instruqt#146]
# Observation

[Hands on lab operator ](https://developers.redhat.com/courses/openshift-operators/go-operator) go breaks in step 1

```sh
FATA[0000] failed to initialize project: already initialized 
````

* Screen shot:

<img width="1199" alt="operator-hands-on-error-2022-09-12" src="https://user-images.githubusercontent.com/12815392/189625954-264cf21b-6610-40c1-9001-a561be84f636.png">

* Output:

```sh
operator-sdk init --domain=example.com --repo=github.com/redhat/podset-operator
Error: failed to initialize project: already initialized
Usage:
  operator-sdk init [flags]

Examples:
  # Initialize a new project with your domain and name in copyright
  operator-sdk init --plugins go/v3 --domain example.org --owner "Your name"

  # Initialize a new project defining a specific project version
  operator-sdk init --plugins go/v3 --project-version 3


Flags:
      --component-config         create a versioned ComponentConfig file, may be 'true' or 'false'
      --domain string            domain for groups (default "my.domain")
      --fetch-deps               ensure dependencies are downloaded (default true)
  -h, --help                     help for init
      --license string           license to use to boilerplate, may be one of 'apache2', 'none' (default "apache2")
      --owner string             owner to add to the copyright
      --project-name string      name of this project
      --project-version string   project version (default "3")
      --repo string              name to use for go module (e.g., github.com/user/repo), defaults to the go package of the current working directory.
      --skip-go-version-check    if specified, skip checking the Go version

Global Flags:
      --plugins strings   plugin keys to be used for this subcommand execution
      --verbose           Enable verbose logging

FATA[0000] failed to initialize project: already initialized
```
# Impact

First steps displays an error of the workshop. It needs to verified if the rest of the hands-on works.

# Trying to fix error 

We can't change initial state for the hands-on lab environment.

# Steps to reproduce

* Open the [lab environment](https://developers.redhat.com/courses/openshift-operators/go-operator)  in Chrome Version 104.0.5112.101 (Official Build) (x86_64)
* Follow the steps until step 1 and you will get the error

FYI @madorn @yuriolisa @nheidloff
This bug is related to https://github.com/openshift-instruqt/instruqt/issues/134

**Comment by blues-man** [comment]
Please try again @thomassuedbroecker , I just pushed an update and change the hot starts, it will take 30 min or so

**Comment by thomassuedbroecker** [comment]
Hi @blues-man,  now it works, thanks

<img width="1899" alt="operator-hands-on-error-2022-09-12-02" src="https://user-images.githubusercontent.com/12815392/189646463-374429cd-93b2-472d-aafe-f8aca27b423c.png">
