### ISSUE TITLE
Capacity Request: Kubecon NA

### ISSUE THREAD

**Issue by ryanj** [openshift-instruqt/instruqt#153]
**Name the event**
Kubecon NA

**Date and time of the event**
Oct 26 - Wednesday Expo Hours: 10:30 - 20:00
Oct 27 - Thursday Expo Hours: 10:30 – 17:30
Oct 28 - Friday Expo Hours: 10:30 – 16:00 

**Event duration**
3 laptops, 2 labs - 6 Hotstarts

**Content Request**
Getting started with OpenShift for Developers
Getting started with Quarkus

**Comment by cedricclyburn** [comment]
Closing this as event has already happened 👍
