### ISSUE TITLE
Singtel Cloudfest Container Hands-on : Capacity Request

### ISSUE THREAD

**Issue by hwng** [openshift-instruqt/instruqt#154]
Singtel Cloudfest Container Hands-on
26th Oct 10:00 AM to 11:00 AM SGT
1 hour. Will be good to keep it running till 12 noon
i.e 2 hours 10:00 AM to 12:00 noon SGT

"Get started with containers"
"Getting Started with ArgoCD and OpenShift GitOps Operator"

Request for 120 hotstarts for the 2 track

**Comment by danieloh30** [comment]
@hwng can you elaborate on the # of hot starts you need as well? For example, 10 hotstarts means 10 laptops.

**Comment by hwng** [comment]
Edited with the no of hotstarts requested.

**Comment by yajuvendrarawat** [comment]
Hello The number of hotstart required are 120 becasue of addition of participants.

regards,
Yaju

**Comment by yajuvendrarawat** [comment]
just to mention that 120 hotstarts required for 2 lessons so total of 240 hotstarts.

regards,
Yaju

**Comment by cedricclyburn** [comment]
For "Getting Started with ArgoCD", `02-connecting-to-argocd` has a missing image called "ArgoCD UI Shortcut, will fix later. Both tracks good to go from flow standpoint

**Comment by cedricclyburn** [comment]
In addition, the screenshot images from the deployed application need to be updated, I'll make a separate issue for that.

**Comment by cedricclyburn** [comment]
Event has passed, closing ticket
