### ISSUE TITLE
Ohio Linux Fest Dec 1st workshop

### ISSUE THREAD

**Issue by jaryan-rh** [openshift-instruqt/instruqt#159]
**Name the event**
Ohio Linux Fest

**Date and time of the event**
Dec 1st 2022 8:00 AM EST

**Event duration**
9 hours

**Content Request**
I am using the subsystems workshop.  There are some minor changes that I am work with Scott on, either he or I will put in the PRs

**Anything else?**
I'm not sure the number of seats we'll need warmed, but probably around 10.  I will know closer to the actual workshop how many participants we have.

**Comment by ryanj** [comment]
Can you provide a list of each of the tracks that you want warmed up?

**Comment by jaryan-rh** [comment]
The Entire Subsystems course

- Introduction to Containers
- Container Images
- Container Registries
- Container Hosts
- Container Orchestration
- Container Standards
- Container Tools Ecosystem

Thanks

**Comment by cedricclyburn** [comment]
Event has passed, closing ticket 👍
