### ISSUE TITLE
no tkn cli in the track "Getting Started with OpenShift Pipelines"

### ISSUE THREAD

**Issue by yajuvendrarawat** [openshift-instruqt/instruqt#162]
**In which track did this bug occur?**

Name the instruqt track that you were using
Getting Started with OpenShift Pipelines

**what is the url for the track?**
https://developers.redhat.com/courses/gitops/getting-started-openshift-pipelines

**At what step of the track did this happen?**
Step 3 - Create Sample Task

**Describe the bug**

**Logs or error messages**
[root@crc-gh9wd-master-0 /]# tkn task start --showlog hello
bash: tkn: command not found
[root@crc-gh9wd-master-0 /]#

**Expected behavior**
tkn command line tool should be available in order to proceed

**Screenshots**
attached

**Desktop (please complete the following information):**
 Chrome

**Smartphone (please complete the following information):**
None

**Additional context**
![Screenshot 2022-11-08 at 5 49 32 PM](https://user-images.githubusercontent.com/43192654/200532396-e4cf8983-d921-44a0-bd6e-6000271a861d.png)

**Comment by cedricclyburn** [comment]
Just confirmed this issue still persists, will work on ASAP

**Comment by cedricclyburn** [comment]
Re-added tkn cli into the Pipelines track, sorry about the delay!
