### ISSUE TITLE
Capacity request for Devops CI/CD event at StarHub

### ISSUE THREAD

**Issue by yajuvendrarawat** [openshift-instruqt/instruqt#163]
**Name the event**
Devops CI/CD event at StarHub

**Date and time of the event**
18/November/2022, 4:00 pm to 6:00 pm SGT

**Event duration**
2 hours

**Content Request**
Our default content will work for this event.  Thank you

**Anything else?**
Total of 10 hotstarts are requested for the event.
TRACK: Getting Started with OpenShift Pipelines
TRACK: Getting Started with ArgoCD and OpenShift GitOps Operator

**Comment by ryanj** [comment]
The following tracks:
    TRACK: Using OpenShift Pipelines
    TRACK: Getting Started with ArgoCD and OpenShift GitOps Operator
have been scheduled to be available for 2.5 hours starting at Nov 18, 2022 / 12:00 AM PST

I think I have the timezone adjusted correctly

**Comment by cedricclyburn** [comment]
Event has passed, closing issue 👍
