### ISSUE TITLE
Can't embed Web Console 

### ISSUE THREAD

**Issue by blues-man** [openshift-instruqt/instruqt#17]
OpenShift Web Console and Oauth server pods has a `X-Frame-Options: deny` options that inhibits their embedding into Instruqt Tabs.

The[ workaround with NGINX NodePort and `proxy_pass`](https://github.com/blues-man/nginx-container/blob/master/examples/1.20/test-app/nginx.conf#L50) doesn't work because the Console contacts the Oauth2 through its route and so the removed headers appears again.

```
Instruqt proxy -> NGINX NodePort -> OpenShift IngressController HAProxy-> Console Pod->OAuth2 Pod
``` 

A solution could be this one
![image (6)](https://user-images.githubusercontent.com/1446126/141466139-db2c2651-9e94-4f26-981b-296ef73a581f.png)

**Comment by yuriolisa** [comment]
Hi, @blues-man , 

I think your proposed solution is feasible. Do you have any place which I could test it?

**Comment by blues-man** [comment]
HI @yuriolisa, what blocked us is the Oauth pod redirects to HAproxy again avoiding NGINX.

But we could create an NGINX container with NodePort with 2 server entries, one for the console and one for the oauth.

We may have basically two options:

- Instruqt proxy intercept any request to console-openshift-console.* and oauth.* and send it to the NGINX 
- We match the headers in some way with iptables and redirect only those two routes to NGINX.

Asking to @amochtar for any other suggestion about it

**Comment by blues-man** [comment]
This is solved by https://github.com/openshift-instruqt/instruqt/issues/62 in another way
