### ISSUE TITLE
Directory typo (opt vs root) in developing-on-openshift-helm

### ISSUE THREAD

**Issue by evanshortiss** [openshift-instruqt/instruqt#174]
**In which track did this bug occur?**

developing-on-openshift-helm

**what is the url for the track?**

https://play.instruqt.com/openshift/tracks/developing-on-openshift-helm

**At what step of the track did this happen?**

First track IIRC

**Describe the bug**

This is a minor issue since it's easy to figure out while following the track. The instructions ask the user to create a helm chart in `/opt` directory, but the subsequent instructions use `/root` and a pre-configured chart folder in root.

**Expected behavior**

Clarity on the directory to use.

**Comment by cedricclyburn** [comment]
Just fixed the docs, thanks for opening this issue!
