### ISSUE TITLE
Call to Action: Sandbox

### ISSUE THREAD

**Issue by ryanj** [openshift-instruqt/instruqt#189]
**Is your feature request related to a problem? Please describe.**
We can offer better next steps following instruction 

**Describe the solution you'd like**
We should provide an example CTA that can be added to tracks - covering next steps:

```
#Congratulations!

Link to:
* Next track in a series (if any)
* Sandbox
* /learn
```

**Comment by cedricclyburn** [comment]
Just to expand a bit on this, here's a basic template I came up with. Meeting today with webops team to discuss a strategy on how we'll generate the custom Sandbox links for metrics tracking.

```
# Next Steps!

Congratulations on completing this self-paced lab and learning about the capabilities of Red Hat OpenShift. To continue your journey, here's some handy links:

* [Continue learning x](https://)
* [Want to try a free, instant 30-day OpenShift cluster? Get started with the Developer Sandbox for Red Hat OpenShift](https://developers.redhat.com/developer-sandbox)
* [Red Hat Developer learning page](https://developers.redhat.com/learn)

Don't forget to finish the lab now and rate the experience via the green button below. Thanks!
```

**Comment by joshix** [comment]
## What's Next?

Congratulations on completing this lab. Keep learning about OpenShift:

* [Continue to the next lab in the X learning path](https://TBD)
* Experiment on a managed cluster free for thirty days with the [Developer Sandbox for Red Hat OpenShift](https://developers.redhat.com/developer-sandbox)
* Visit the [Red Hat Developer learning page](https://developers.redhat.com/learn) for more labs  and resources

Rate your experience with this lab by using the green button below. Thanks for playing!

**Comment by cedricclyburn** [comment]
Also, @blues-man mentioned to send DTBU an email dtbu-all@redhat  update notifying of new CTA implemented in our self-paced labs once we're finished 👍

**Comment by ryanj** [comment]
I'm going to work on adding this to the playground first, then we will target [these tracks](https://www.redhat.com/en/interactive-labs/openshift) and our other top tracks 

- [x] [ OpenShift Playground](https://play.instruqt.com/openshift/tracks/playgrounds-openshift411-dev)
- [x] Getting Started with OpenShift for Developers
- [x] Getting Started with DevOps (ArgoCD)
- [x] Pipelines
- [x] Log in to a Red Hat OpenShift cluster

**Comment by cedricclyburn** [comment]
Perhaps modify CTA for ArgoCD to OpenShift Local as no ArgoCD operator for Sandbox

**Comment by ryanj** [comment]
example copy:
```
# What's Next?

Congratulations on completing this lab. Keep learning about OpenShift:

* Visit the [Red Hat Developer learning page](https://developers.redhat.com/learn) for more labs and resources
* [Want to try a free, instant 30-day OpenShift cluster? Get started with the Developer Sandbox for Red Hat OpenShift](https://developers.redhat.com/developer-sandbox)

Don't forget to finish the lab and rate your experience on the next page. Thanks for playing!
```

**Comment by joshix** [comment]
I rewrote the model CTA in https://github.com/openshift-instruqt/instruqt/issues/189#issuecomment-1409134402. Did we not like that copy and used the older revision intentionally, or was that just an oversight?

**Comment by joshix** [comment]
> Perhaps modify CTA for ArgoCD to OpenShift Local as no ArgoCD operator for Sandbox

* Gain cluster-wide control with a virtual OpenShift on your laptop with [OpenShift Local](URL)

Can either replace bullet number 2 in either of the versions of the model CTA copy OR join it in the list
