### ISSUE TITLE
Hot Starts: DeveloperWeek 2023 - Feb 15-17

### ISSUE THREAD

**Issue by evanshortiss** [openshift-instruqt/instruqt#200]
**Name the event**
DeveloperWeek 2023

**Date and time of the event**
February 15-17th (Pacific Time)

**Event duration**
8 hours

**Content Request**
* Developing with Quarkus Getting Started (Short)
* Getting Started with OpenShift
* OpenShift 4.11 Playground

**Comment by cedricclyburn** [comment]
Event was a success! 🥳
