### ISSUE TITLE
Routes considered ready for use before required FQDN patch is complete

### ISSUE THREAD

**Issue by jdandrea** [openshift-instruqt/instruqt#223]
**In which track did this bug occur?**
Getting Started with ArgoCD and OpenShift GitOps Operator

**what is the url for the track?**
https://developers.redhat.com/courses/gitops/getting-started-argocd-and-openshift-gitops-operator

**At what step of the track did this happen?**
Step One (OCP Console, OAuth, and GitOps Server URIs are ostensibly ready)

**Describe the bug**
GitOps Server URI not patched, yet the resource is considered ready. Same situation at times for the OAuth URI.

**Logs or error messages**
e.g., GitOps Server URI is https://openshift-gitops-server-openshift-gitops.apps-crc.testing/ (presumably this is the unpatched URI template)

**Expected behaviour**
GitOps Server URI expected to be patched along these lines: https://openshift-gitops-server-openshift-gitops.crc-OCP_CLUSTER_ID-master-0.crc.INSTRUQT_INSTANCE_ID.instruqt.io/

**Desktop (please complete the following information):**
 - macOS
 - Chrome 109.0.5414.119 (Official / arm64)
 - Ventura 13.2.1

**Additional context**
At around 4:30pm EST 21 Feb 2023, the Cluster API was unreachable/unresponsive a few times. Perhaps the URI patching logic could stand some extra reinforcements in this regard? 

Example:
```
[root@crc-lgph7-master-0 /]# oc get route -n openshift-console
Error from server (ServiceUnavailable): the server is currently unable to handle the request (get routes.route.openshift.io)
```

Then again, when I tried at 9:25am EST 22 Feb 2023, the GitOps Server URI was also unpatched. There may be a combination of things in play here.

**Comment by jdandrea** [comment]
Possible Workaround: Tried `oc delete route openshift-gitops-server` then poked at the `openshift-gitops-server` Deployment in hopes of instigating things. I should have just done one thing or the other, however at this point the route _is_ as expected and working.

So... not solved, and at the same time there may be a way to clear the logjam in the interim.

**Comment by jdandrea** [comment]
Ok, the workaround for me was to delete the route, at which point it was recreated/patched as expected.

```
[root@crc-lgph7-master-0 /]# oc project openshift-gitops
Now using project "openshift-gitops" on server "https://api.crc.testing:6443".
[root@crc-lgph7-master-0 /]# oc get route openshift-gitops-server
NAME                      HOST/PORT                                                   PATH   SERVICES  PORT    TERMINATION            WILDCARD
openshift-gitops-server   openshift-gitops-server-openshift-gitops.apps-crc.testing          openshift-gitops-server  https   passthrough/Redirect   None
[root@crc-lgph7-master-0 /]# oc delete route openshift-gitops-server
route.route.openshift.io "openshift-gitops-server" deleted
[root@crc-lgph7-master-0 /]# oc get route openshift-gitops-server
NAME                      HOST/PORTPATH   SERVICES                  PORT    TERMINATION            WILDCARD
openshift-gitops-server   openshift-gitops-server-openshift-gitops.crc-lgph7-master-0.crc.lcgy1clfvzfl.instruqt.io       openshift-gitops-server   https   passthrough/Redirect   None
```

**Comment by ryanj** [comment]
Thanks for reporting - I'll look into it

**Comment by ryanj** [comment]
This should be fixed. Feel free to reopen if you see the issue again
