### ISSUE TITLE
Test Sandbox Prestarts 

### ISSUE THREAD

**Issue by ryanj** [openshift-instruqt/instruqt#232]
Goal: Determine what work is required to build prestart-compatible tracks. Collect feedback on prestart performance

We are currently testing sandbox prestarts for the following tracks:

- [x] [playground 4-12](https://play.instruqt.com/openshift/tracks/playgrounds-openshift412) 4-12
- [x] [playground 4-11](https://play.instruqt.com/openshift/tracks/playgrounds-openshift411) 4-11
- [x] [getting started (short)](https://play.instruqt.com/openshift/tracks/getting-started-with-openshift) 4-11
- [x] [getting started](https://play.instruqt.com/openshift/tracks/developing-on-openshift-getting-started) 4-11
- [x] [Logging in to an OpenShift Cluster](https://play.instruqt.com/openshift/tracks/using-the-cluster-cluster-access) 4-11
- [x] [GitOps Pipelines](https://play.instruqt.com/openshift/tracks/gitops-pipelines-short) 4-11
- [x] [GitOps Pipelines (short)](https://play.instruqt.com/openshift/tracks/gitops-pipelines-short) 4-11
- [ ] [Getting Started with Quarkus (short)](https://play.instruqt.com/openshift/tracks/developing-with-quarkus-getting-started-short) 4-11
- [ ] [Getting Started with Quarkus](https://play.instruqt.com/openshift/tracks/developing-with-quarkus-getting-started) 4-11
- [x] [Quarkus for spring boot developers](https://play.instruqt.com/openshift/tracks/developing-with-quarkus-spring) 4-11
- [ ] [Apache Kafka with Reactive Messaging](https://play.instruqt.com/openshift/tracks/kafka-kafka-quarkus) 4-11
- [ ] [Getting Started with ArgoCD](https://play.instruqt.com/openshift/tracks/gitops-getting-started) 4-11 LARGE
- [ ] [developing-on-openshift-developing-with-odo](https://play.instruqt.com/openshift/tracks/developing-on-openshift-developing-with-odo) 4-11 + fedora

Migration Next Steps (for each track):

  1. All tracks that include customizations to `track_scripts/setup-crc` must have those lines moved to `01-step1/setup-crc` (where "01-step1" is the name of the first challenge folder).   Similarly, any customizations to "track_scripts/setup-container" must be relocated to "01-step1/setup-container" when using a sidecars with differentiated content.  Check for differences wby running the following from within the track folder: `diff track_scripts/setup-crc ../../examples/preset/track_scripts/setup-crc`
  2. For each track, add a preset definition to the `track.yml` file - See: https://github.com/openshift-instruqt/instruqt/pull/236/files#diff-dc5d411d2b8e17c72ed214877c8eafd0319380bb57d620f2fefb7fdf90c33cc2R33
  3. For each track, remove `config.yml` and the `track_scripts` folder: `git rm -rf config.yml track_scripts`
 
In the Repo:
  1. Update example tracks
  2. Update README instructions
  3. Prioritize conversion for top tracks by usage: https://play.instruqt.com/openshift/statistics
  4. Prioritize conversion for tracks used at events ✅ : #238
  5. Prioritize conversion for tracks listed on RH.com ✅ : #237

Tracks that require minimal effort to add to a scaling group. Check marks indicate prestart is enabled for these tracks:
- [ ] [Application Messaging with Openshift](https://play.instruqt.com/openshift/tracks/enterprise-java-amq-getting-started-broker)
- [ ] [Red Hat Data Grid development](https://play.instruqt.com/openshift/tracks/enterprise-java-rhoar-getting-started-rhdg)
- [ ] [Operator Lifecycle Manager](https://play.instruqt.com/openshift/tracks/operatorframework-operator-lifecycle-manager)
- [ ] [Persistent Storage for Elasticsearch Powered by OpenShift Container Storage](https://play.instruqt.com/openshift/tracks/persistence-persistent-elasticsearch)
- [ ] [Making Persistent Storage Calls in Your Application](https://play.instruqt.com/openshift/tracks/persistence-persistent-intro)
- [ ] [Serverless Eventing with Camel K](https://play.instruqt.com/openshift/tracks/serverless-camel-k-eventing)
- [ ] [Serverless Camel K](https://play.instruqt.com/openshift/tracks/serverless-camel-k-serving)
- [ ] [Camel Kafka Connector Basics](https://play.instruqt.com/openshift/tracks/serverless-camel-kafka-connector)

**Comment by cedricclyburn** [comment]
Currently, these tracks (from above) don't yet have a preset enabled:
- [Getting Started with OpenShift for Developers](https://play.instruqt.com/openshift/tracks/developing-on-openshift-getting-started)
- [Logging in to an OpenShift Cluster](https://play.instruqt.com/openshift/tracks/using-the-cluster-cluster-access)
- [Getting Started with Quarkus](https://play.instruqt.com/openshift/tracks/developing-with-quarkus-getting-started)
- [Getting Started with Quarkus - QuickStart](https://play.instruqt.com/openshift/tracks/developing-with-quarkus-getting-started-short)
- [Apache Kafka with Reactive Messaging](https://play.instruqt.com/openshift/tracks/kafka-kafka-quarkus)

Gonna work on making sure they all do on Git/Web, and will update once finished!
