### ISSUE TITLE
OpenShift Outage: All tracks fail to load

### ISSUE THREAD

**Issue by yajuvendrarawat** [openshift-instruqt/instruqt#246]
**In which track did this bug occur?**
None of the labs which are mentioned in https://www.redhat.com/en/interactive-labs/openshift are working
Name the instruqt track that you were using
All
**what is the url for the track?**
Provide a url where you discovered the content issue
All

**At what step of the track did this happen?**
When we start

If you can't remember the exact step, try to explain where in the track did the bug happen

**Describe the bug**

**Logs or error messages**
Paste in any error message you received

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Browser Chrome

**Additional context**
![Screenshot 2023-05-02 at 10 33 47 AM](https://user-images.githubusercontent.com/43192654/235569289-d34d0633-7680-41f9-9fe0-e84b73ad3cd3.png)
![Screenshot 2023-05-02 at 10 33 36 AM](https://user-images.githubusercontent.com/43192654/235569309-41816609-6c4b-4ee5-95ab-4f8213391b02.png)
![Screenshot 2023-05-02 at 10 33 27 AM](https://user-images.githubusercontent.com/43192654/235569321-e59a8ef8-e997-4130-a9a0-2e0b2314346d.png)
![Screenshot 2023-05-02 at 10 33 12 AM](https://user-images.githubusercontent.com/4
![Screenshot 2023-05-02 at 10 33 01 AM](https://user-images.githubusercontent.com/43192654/235569348-2484d768-a6b9-491d-bd5f-f9bf3fdb1e61.png)
3192654/235569334-677a71cc-d4ac-47f0-8ab9-5e5631c379af.png)

**Comment by ryanj** [comment]
Thanks for reporting - we will look into it

**Comment by ryanj** [comment]
This appears to be impacting 100% of our tracks!  Will raise the issue with instruqt support to see what is going on

**Comment by ryanj** [comment]
This has been resolved.  Thanks again for the alert @yajuvendrarawat
