### ISSUE TITLE
Customer event 5/10

### ISSUE THREAD

**Issue by evanstoner** [openshift-instruqt/instruqt#247]
**Name the event**
Public sector customer event

**Date and time of the event**
5/10 12pm-4pm

**Event duration**
4 hours

**Content Request**
Lesson 1 - Build and deploy applications with OpenShift
Lesson 5 - Deploy applications from source code

**Anything else?**
Number of attendees: 20

**Comment by ryanj** [comment]
I'm not sure if I have the correct track links...  I currently have a hot start configured for these two:

* [Getting Started with OpenShift for Developers](https://developers.redhat.com/courses/foundations/getting-started)
* [Deploying Applications From Source](https://developers.redhat.com/courses/openshift/deploying-python)

If I've included the wrong tracks, please send updated track urls and I'll update the hot start configuration.

**Comment by evanstoner** [comment]
Those are the ones, thanks! Will comment back when we're wrapped up.

**Comment by evanstoner** [comment]
Obviously forgot to comment back at the end of the day but thank you! We had some UI issues I'll share with the team next week after I can review my notes.
