### ISSUE TITLE
The time limit for this track is too short: cicd-with-ansible-automation-platform-and-jenkins-on-openshift 

### ISSUE THREAD

**Issue by rh-bjeon** [openshift-instruqt/instruqt#248]
**In which track did this bug occur?**
[cicd-with-ansible-automation-platform-and-jenkins-on-openshift](https://github.com/openshift-instruqt/instruqt/tree/master/instruqt-tracks/cicd-with-ansible-automation-platform-and-jenkins-on-openshift)

**what is the url for the track?**
[Provide a url where you discovered the content issue](https://developers.redhat.com/courses/cicd-ansible-automation-platform-and-jenkins-openshift)

**At what step of the track did this happen?**
The entire track

**Describe the bug**
The time limit set for this track is too short, 600 seconds. Deploying the ansible automation platform in the first challenge alone takes at least a few minutes.

It seems necessary to delete or increase the timeout from the track settings(https://github.com/openshift-instruqt/instruqt/blob/master/instruqt-tracks/cicd-with-ansible-automation-platform-and-jenkins-on-openshift/track.yml).

**Logs or error messages**
Paste in any error message you received

**Expected behavior**
The track shouldn't stop while I'm doing the challenge nonstop.

**Comment by rh-bjeon** [comment]
I have to wait 4-5 minutes after starting the track to get access to the OpenShift cluster.
And I have to wait another 10 minutes for the Ansible Automation controller to be deployed and running...
While waiting, the track stops due to a timeout in the first challenge. :(

This page estimates that it will take 30 minutes to complete this track.
(https://developers.redhat.com/learn)

**Comment by nageshredhat** [comment]
Hi @rh-bjeon,
Thanks for pointing out the issue. 
we will update you soon.

**Comment by nageshredhat** [comment]
Hello @rh-bjeon,
lab time extended to 1 hour, please check.

**Comment by cedricclyburn** [comment]
Closing as this looks like it's been resolved!
