### ISSUE TITLE
Globe: NTG Openshift Hands-on : Capacity Request

### ISSUE THREAD

**Issue by karunrk** [openshift-instruqt/instruqt#251]
**Name the event**
Network Technology Group (NTG) day at Globe Telecom Philippines

**Date and time of the event**
21-June-2023, 9AM - 6PM Philippines Times (GMT+8)

**Event duration**
How many hours will this event be active?  8 hours? (please schedule one request per day)
8 Hours (1 Day)

**Content Request**
Our default content will work for this event.  Thank you
Default content for the below Labs:

Get started with containers
https://developers.redhat.com/courses/subsystems/intro

Manage your containers
https://developers.redhat.com/courses/subsystems/management

Getting Started with OpenShift Pipelines
https://developers.redhat.com/courses/gitops/getting-started-openshift-pipeline

**Anything else?**
Additional details...

Request for 30 hotstarts for 3 labs. 
ie. 90 hoststarts in total

**Comment by cedricclyburn** [comment]
Hello @karunrk, currently our Pipelines lab is broken to due to an update, are there any other labs you'd like to request perhaps? Will update you if it's fixed in the meantime. @ryanj

**Comment by karunrk** [comment]
Hi @cedricclyburn , can we replace pipelines with  "Deploying Applications From Source"

**Comment by cedricclyburn** [comment]
Good to go! @karunrk 

<img width="700" alt="image" src="https://github.com/openshift-instruqt/instruqt/assets/54345140/bfc1eaf5-4ebf-4c00-93a6-08779246d265">

**Comment by karunrk** [comment]
Thanks @cedricclyburn .
Do we have a dedicated link to show these labs with hotstarts?

If yes, please help to share.

**Comment by cedricclyburn** [comment]
Do we happen to @ryanj? If not, just visiting the regular labs link should work!

**Comment by karunrk** [comment]
Hi Team, It was a successful hands-on session for the customer. Thanks a lot for your support. 
Team did identify an error in the first lab, not a blocker though. Will share it over email
Thanks again

**Comment by cedricclyburn** [comment]
Okay gotcha, happy to help! Yes, please share @karunrk, we're doing a summer cleanup right now for these labs and would love to improve them :)
