### ISSUE TITLE
kubectl client-side throttling

### ISSUE THREAD

**Issue by yuriolisa** [openshift-instruqt/instruqt#26]
The following message is being presented when we try to get pods using kubectl instead oc:

`[root@crc-dzk9v-master-0 /]# kubectl get pods
I1122 11:45:52.315112 1772227 request.go:665] Waited for 1.17392018s due to client-side throttling, not priority and fairness, request: GET:https://api.crc.testing:6443/apis/controlplane.operator.openshift.io/v1alpha1?timeout=32s
No resources found in myproject namespace.
[root@crc-dzk9v-master-0 /]# oc get pods
No resources found in myproject namespace.
`

**Comment by ryanj** [comment]
Sorry about the delay...  updating with new info:  
Instruqt tracks that use `dzk9v-master-0` have all been upgraded to use newer releases of OpenShift.  Feel free to reopen if you hit this issue again

Thanks for raising the alert
