### ISSUE TITLE
build log can not show

### ISSUE THREAD

**Issue by mayumi00** [openshift-instruqt/instruqt#269]
**In which track did this bug occur?**
Deploying Applications From Source

**what is the url for the track?**
https://play.instruqt.com/openshift/tracks/using-the-cluster-deploying-python

**At what step of the track did this happen?**
Topic 3 - Viewing the build logs in the Web Console
Topic 6 - Deploying the application from the command line

**Describe the bug**
Topic 3 - Viewing the build logs in the Web Console
`Step 3: Click the View logs button as shown in the figure below.`
I clicked the button, but I don't see any logs.

Topic 6 - Deploying the application from the command line
`Step 2: Run the following command to monitor the log output from the build as it is running:`
oc logs bc/blog-django-py --follow

I don't see any logs.

**Logs or error messages**
n/a

**Expected behavior**
build logs shown

**Screenshots**

**Desktop (please complete the following information):**
 - macOS
 - Firefox 116.0.2
 - ventura 13.5

**Additional context**

**Comment by cedricclyburn** [comment]
Fixed with https://github.com/openshift-instruqt/instruqt/pull/275
