### ISSUE TITLE
Ansible Operator Overview: unknown flag: --generate-role

### ISSUE THREAD

**Issue by blues-man** [openshift-instruqt/instruqt#27]
From Step 5, this command fails:

```
root@container:~/tutorial# operator-sdk create api --group app --version v1alpha1 --kind App --generate-role
Error: unknown flag: --generate-role
```

**Comment by yuriolisa** [comment]
I just checked the ansible issue and this `--generate-role` is presented only on `operator-sdk init --plugins ansible -h`. 
Then I can confirm that flag should not be there.

**Comment by blues-man** [comment]
thanks!
