### ISSUE TITLE
can't access the POD using oc rsh command

### ISSUE THREAD

**Issue by mayumi00** [openshift-instruqt/instruqt#270]
**In which track did this bug occur?**
Transferring Files in and out of Containers

**what is the url for the track?**
https://play.instruqt.com/openshift/tracks/using-the-cluster-transferring-file

**At what step of the track did this happen?**
Topic 2 - Downloading Files from a Container

**Describe the bug**
`Step 6: Run the following oc rsh command to open an interactive command shell within the pod whose name is defined in the environment variable POD:``

I can't access the POD using oc rsh command.

**Logs or error messages**
[root@crc-lgph7-master-0 /]# POD=$(oc get pods --selector deployment=simplemessage -o custom-columns=NAME:.metadata.name --no-headers); echo $POD
simplemessage-5dc4d7d66f-7kmvl

[root@crc-lgph7-master-0 /]# oc rsh $POD
error: unable to upgrade connection: Unauthorized

**Expected behavior**
I can access using oc rsh command and shown prompt below.
sh-4.2$

**Screenshots**

**Desktop (please complete the following information):**
 - macOS
 - Firefox 116.0.2
 - ventura 13.5

**Additional context**

**Comment by cedricclyburn** [comment]
Fixed with https://github.com/openshift-instruqt/instruqt/pull/275
