### ISSUE TITLE
Singtel Cloudfest Container Hands-on : Capacity Request

### ISSUE THREAD

**Issue by yajuvendrarawat** [openshift-instruqt/instruqt#271]
**Name the event**
Singtel Cloudfest Container Hands-on

**Date and time of the event**
4 Sept 2023, from 9:00 AM to 01:00 PM. SGT

**Event duration**
4 Hours.

**Content Request**
- Get started with Red Hat OpenShift for developers
- Get started with Argo CD and GitOps with Red Hat OpenShift
- Use Red Hat OpenShift Pipelines

**Anything else?**
Request for 100 hotstarts for each track for 4 hours.

**Comment by cedricclyburn** [comment]
Cleaning this up, thanks!
