### ISSUE TITLE
Red Hat Summit: Connect Darmstadt

### ISSUE THREAD

**Issue by sebastianfaulhaber** [openshift-instruqt/instruqt#273]
**Name the event**
Openshift, AI and Automation for All Operators

**Date and time of the event**
November 30, 2023
12.00 - 19.00 CET

**Event duration**
7 hours

**Content Request**
[Log in to a Red Hat OpenShift cluster](https://www.redhat.com/en/interactive-labs/log-in-red-hat-openshift-cluster)
[Getting Started with OpenShift for Developers](https://www.redhat.com/en/interactive-labs/get-started-red-hat-openshift-developers)
[Use Red Hat OpenShift Pipelines](https://www.redhat.com/en/interactive-labs/use-red-hat-openshift-pipelines)
[Get started with Argo CD and GitOps](https://www.redhat.com/en/interactive-labs/get-started-argo-cd-gitops-red-hat-openshift)   
[Overview: Using OpenShift](https://developers.redhat.com/learn/openshift/using-openshift)
[Overview: Developing applications on OpenShift](https://developers.redhat.com/learn/openshift/develop-on-openshift)
[Overview: DevOps on OpenShift](https://developers.redhat.com/learn/openshift/devops-openshift)

**Anything else?**
We expect ~30 users working through the labs and kindly reuest enough hotstarts. Thank you very much!

**Comment by sebastianfaulhaber** [comment]
We do have 38 registered users for the event as of today. Would you be so kind to add capacity for up to 50 users. Thank you so much!

**Comment by cedricclyburn** [comment]
<img width="860" alt="Screenshot 2023-11-16 at 1 10 11 PM" src="https://github.com/openshift-instruqt/instruqt/assets/54345140/130cbb3a-c2ab-41dc-a94b-1df09ed1b63a">
Here we are @sebastianfaulhaber!

**Comment by sebastianfaulhaber** [comment]
Thank you very much @cedricclyburn !
