### ISSUE TITLE
ALL OpenShift 4.11 labs cannot access pods logs

### ISSUE THREAD

**Issue by blues-man** [openshift-instruqt/instruqt#274]
**In which track did this bug occur?**

- Getting Started with OpenShift Pipelines
- Get started with Argo CD and GitOps with Red Hat OpenShift
- OpenShift Playground 4.11

**what is the url for the track?**

https://developers.redhat.com/learn/openshift/devops-openshift

**At what step of the track did this happen?**

```kubectl logs <name_of_the_pod>```

```oc logs <name_of_the_pod>```

**Describe the bug**

Apparently to some certificate expire issue, kubectl logs doesn't work anymore in this 4.11 image.

**Logs or error messages**

``` [root@crc-lgph7-master-0 /]# oc version
Client Version: 4.11.0-202209201358.p0.g262ac9c.assembly.stream-262ac9c
Kustomize Version: v4.5.4Server Version: 4.11.7
Kubernetes Version: v1.24.0+3882f8f
[root@crc-lgph7-master-0 /]# tkn task start --showlog helloTaskRun started: hello-run-lpb72Waiting for logs to be available...
error in getting logs for step say-hello: error getting logs for pod hello-run-lpb72-pod(step-say-hello) : the server has asked for the client to provide credentials ( pods/log hello-run-lpb72-pod)
[root@crc-lgph7-master-0 /]# kubectl logs hello-run-lpb72-pod
Defaulted container "step-say-hello" out of: step-say-hello, prepare (init)
error: You must be logged in to the server (the server has asked for the client to provide credentials ( pods/log hello-run-lpb72-pod))
```
**Expected behavior**

kubectl logs
oc logs
tkn task logs

work

**Screenshots**

**Desktop (please complete the following information):**

All
**Smartphone (please complete the following information):**

All

**Additional context**

All 4.11 images are broken

**Comment by cedricclyburn** [comment]
- Fixed Pipelines with https://github.com/openshift-instruqt/instruqt/commit/78bb0f60a304bffa2dafcff176a29f985271d507
- Fixed odo with https://github.com/openshift-instruqt/instruqt/commit/97757b004456050ad1a62faa4d3dd83e6759d4cd

**Comment by cedricclyburn** [comment]
The rest of the labs with the issue have been fixed with https://github.com/openshift-instruqt/instruqt/pull/275
