### ISSUE TITLE
Content QA :: Adding Persistence to OpenShift

### ISSUE THREAD

**Issue by blues-man** [openshift-instruqt/instruqt#37]
TODO: Review the converted content and check if commands are working, if not, go ahead and fix it in the source repo.

Main Instruqt Page: https://play.instruqt.com/openshift
Main Source Code: https://github.com/openshift-instruqt/instruqt

- [ ] [Making Persistent Storage Calls in Your Application](https://play.instruqt.com/openshift/tracks/persistence-persistent-intro) | [Track](https://github.com/openshift-instruqt/instruqt/blob/master/persistence/persistent-intro/track.yml)
- [ ] [Persistent Storage for Elasticsearch Powered by OpenShift Container Storage](https://play.instruqt.com/openshift/tracks/persistence-persistent-elasticsearch) | [Track](https://github.com/openshift-instruqt/instruqt/blob/master/persistence/persistent-elasticsearch/track.yml)

**Comment by cedricclyburn** [comment]
Tracks have been migrated, closing out this issue 👍
