### ISSUE TITLE
Need to enable LE certificate for OpenShift Web Console

### ISSUE THREAD

**Issue by danieloh30** [openshift-instruqt/instruqt#42]
When a student accesses OpenShift Web Console, the following security warning is shown:
![image](https://user-images.githubusercontent.com/14066977/143162304-db2d40ce-f062-4d38-8d02-0f7de72d6b55.png)

To fix this issue, the LE certificate should be enabled in OpenShift Cluster.

**Comment by blues-man** [comment]
We should use ZeroSSL which is also [supporting ACME](https://zerossl.com/features/acme/) due to the rate limiting of LE

**Comment by ryanj** [comment]
This issue should be resolved when using the openshift 4-16 image.  Let me know if you have any questions about how to update.
Individual tracks still need to be updated to use the new image...
