### ISSUE TITLE
Add GitHub Actions for PRs

### ISSUE THREAD

**Issue by blues-man** [openshift-instruqt/instruqt#65]
This is nice example on how we could do:

https://github.com/ansible/instruqt/blob/devel/.github/workflows/ansible/roles/instruqt-track-test/tasks/main.yml

**Comment by ryanj** [comment]
More docs on this topic here: https://docs.instruqt.com/how-to-guides/build-tracks/maintain-a-developer-workflow

**Comment by cedricclyburn** [comment]
To be added in #182, great work @ryanj
