### ISSUE TITLE
Missing  cd `cmd` in operatorframework-helm-operator-workshop

### ISSUE THREAD

**Issue by acornett21** [openshift-instruqt/instruqt#66]
When going to Update the Watches File in `operatorframework-helm-operator-workshop` there should be a cd cmd before the `cat` cmd. Please add the below.

`cd projects/cockroachdb-operator/` to the instructions

**Comment by madorn** [comment]
Just a heads up that this appears in other steps within this module as well. I don't think the present working directory is maintained between steps.

**Comment by acornett21** [comment]
@madorn I only searched for where the `watches.yaml` file was mentioned, the other placed mentioned already had a `cd`.
