### ISSUE TITLE
Sanitize timelimit

### ISSUE THREAD

**Issue by blues-man** [openshift-instruqt/instruqt#77]
We should set all long tracks to run at least 50 minutes, please verify with your tracks and push changes

**Comment by danieloh30** [comment]
FYI, I have already set 50 mins for all Spring Boot and Quarkus tracks.

**Comment by cedricclyburn** [comment]
Fixed for the Cluster/Developing tracks in #82

**Comment by cedricclyburn** [comment]
Updated timelimits recently based on user feedback #171, closing 👍
