### ISSUE TITLE
OpenShift Playground workshop - Mar 10 - 11:00AM to 12:00PM Australian Eastern Daylight Time (AEDT)

### ISSUE THREAD

**Issue by lijcam** [openshift-instruqt/instruqt#87]
OpenShift Playground workshop - Mar 10 - 11:00AM to 12:00PM Australian Eastern Daylight Time (AEDT)

35 attendees

@blues-man
@cedricclyburn

**Comment by blues-man** [comment]
This is created @lijcam, details are in your mail box.

Thanks!
