### ISSUE TITLE
Troubleshooting Basics workshop - May 18 - 11:00AM to 12:00PM Australian Eastern Daylight Time (AEDT) 

### ISSUE THREAD

**Issue by lijcam** [openshift-instruqt/instruqt#93]
Opening this for visibility. I'll setup the hot-starts and invites on my side.
Troubleshooting Basics workshop - May 18 - 11:00AM to 12:00PM Australian Eastern Daylight Time (AEDT)
20 attendees

@blues-man

**Comment by cedricclyburn** [comment]
Closing out since event has passed.
